#!/usr/bin/env bash
# shellcheck shell=bash
## @file tests/megalinter.bash
## @brief Exercises dclint through a real MegaLinter plugin load.
## @details
## Runs the descriptor named by `DCLINT_DESCRIPTOR`, defaulting to the
## maintained development descriptor, against deterministic local Docker Compose
## fixtures. The passing fixture must succeed. A set of intentionally invalid
## fixtures using distinct supported Compose filename forms must all be selected
## and reported by dclint.
##
## MegaLinter requires local plugin descriptors to be hosted beneath a directory
## whose name contains `mega-linter-plugin-`. The selected descriptor is copied
## byte-for-byte into a temporary staging directory with that naming convention
## before MegaLinter loads it. The copy is compared with the selected descriptor
## before use so release integration still exercises the exact generated bytes.
##
## MegaLinter errors are explicitly enabled so dclint failures must affect the
## process exit status.

set -euo pipefail

readonly DCLINT_EX_NOINPUT=66
readonly DCLINT_EX_SOFTWARE=70
readonly MEGALINTER_IMAGE="${MEGALINTER_IMAGE:-ghcr.io/oxsecurity/megalinter-ci_light:v10.1.0}"
readonly DCLINT_DESCRIPTOR="${DCLINT_DESCRIPTOR:-mega-linter-plugin-dclint/dclint.megalinter-descriptor.yml}"
readonly PLUGIN_STAGE_DIR="test-results/mega-linter-plugin-dclint-release"
readonly PLUGIN_STAGE_DESCRIPTOR="${PLUGIN_STAGE_DIR}/dclint.megalinter-descriptor.yml"
readonly BAD_OUTPUT="test-results/dclint-bad-fixtures.log"

## @fn stage_plugin_descriptor()
## @brief Stages the selected descriptor where MegaLinter accepts local plugins.
## @details
## Copies the selected descriptor into a test-results directory whose name
## satisfies MegaLinter's local plugin path convention, then verifies that the
## staged file is byte-identical to the selected descriptor.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Nothing is written to STDOUT.
## @par STDERR
## A diagnostic is written if the source descriptor is unreadable, staging fails,
## or the staged bytes differ from the source bytes.
##
## @returns Nothing is written to STDOUT.
## @retval 0 The descriptor was staged and verified.
## @retval 66 The selected descriptor is not readable.
## @retval 70 The staging directory, copy, or byte comparison failed.
stage_plugin_descriptor() {
  if [[ ! -r ${DCLINT_DESCRIPTOR} ]]; then
    printf 'Descriptor is not readable: %s\n' "${DCLINT_DESCRIPTOR}" >&2
    return "${DCLINT_EX_NOINPUT}"
  fi

  if ! mkdir -p -- "${PLUGIN_STAGE_DIR}"; then
    printf 'Unable to create plugin staging directory: %s\n' "${PLUGIN_STAGE_DIR}" >&2
    return "${DCLINT_EX_SOFTWARE}"
  fi

  if ! cp -- "${DCLINT_DESCRIPTOR}" "${PLUGIN_STAGE_DESCRIPTOR}"; then
    printf 'Unable to stage plugin descriptor: %s\n' "${DCLINT_DESCRIPTOR}" >&2
    return "${DCLINT_EX_SOFTWARE}"
  fi

  if ! cmp -s -- "${DCLINT_DESCRIPTOR}" "${PLUGIN_STAGE_DESCRIPTOR}"; then
    printf '%s\n' 'Staged plugin descriptor differs from the selected descriptor.' >&2
    return "${DCLINT_EX_SOFTWARE}"
  fi
}

## @fn run_megalinter()
## @brief Runs dclint through MegaLinter against an explicit JSON file list.
## @param files_json JSON array of repository-relative fixture paths.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## MegaLinter writes its ordinary console report to STDOUT.
## @par STDERR
## MegaLinter and Docker diagnostics may be written to STDERR.
##
## @returns MegaLinter's console report.
## @retval 0 dclint accepted the selected fixtures.
## @note Non-zero Docker, plugin-install, dclint, or MegaLinter statuses are
## propagated unchanged.
run_megalinter() {
  local files_json=$1
  local plugin_uri="file://${PLUGIN_STAGE_DESCRIPTOR}"

  docker run \
    --rm \
    -v "${PWD}:/tmp/lint" \
    -w /tmp/lint \
    -e VALIDATE_ALL_CODEBASE=true \
    -e DISABLE_ERRORS=false \
    -e PRINT_ALPACA=false \
    -e SARIF_REPORTER=false \
    -e REPORT_OUTPUT_FOLDER=/tmp/megalinter-reports \
    -e "PLUGINS=[\"${plugin_uri}\"]" \
    -e ENABLE_LINTERS='["DOCKERFILE_DCLINT"]' \
    -e "MEGALINTER_FILES_TO_LINT=${files_json}" \
    "${MEGALINTER_IMAGE}"
}

stage_plugin_descriptor

if ! run_megalinter '["tests/fixtures/docker-compose.yml"]'; then
  printf '%s\n' 'Expected the compliant Docker Compose fixture to pass.' >&2
  exit 1
fi

bad_fixtures=(
  "tests/fixtures/compose.yml"
  "tests/fixtures/compose.yaml"
  "tests/fixtures/docker-compose.override.yml"
  "tests/fixtures/compose/docker-compose-service.yml"
)

bad_json='["tests/fixtures/compose.yml","tests/fixtures/compose.yaml","tests/fixtures/docker-compose.override.yml","tests/fixtures/compose/docker-compose-service.yml"]'

if run_megalinter "${bad_json}" > "${BAD_OUTPUT}" 2>&1; then
  cat "${BAD_OUTPUT}"
  printf '%s\n' 'Expected the invalid Compose fixtures to fail.' >&2
  exit 1
fi

cat "${BAD_OUTPUT}"

for fixture in "${bad_fixtures[@]}"; do
  if ! grep -Fq -- "${fixture}" "${BAD_OUTPUT}"; then
    printf 'Expected dclint output to include selected fixture: %s\n' "${fixture}" >&2
    exit 1
  fi
done
